import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Branding & Header
    'app.name': 'CareAI',
    'app.tagline': 'Helping seniors stay on schedule. Helping families stay informed.',
    'app.subtitle': 'Smart Elderly Healthcare Reminder & Escalation Platform',
    
    // Navigation & Common
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.elderly': 'Elderly View',
    'nav.caregiver': 'Caregiver View',
    'nav.medicines': 'Medications',
    'nav.history': 'History',
    'nav.notifications': 'Notifications',
    'nav.assistant': 'AI Assistant',
    'nav.settings': 'Settings',
    'nav.demo': 'Demo Simulation',
    'nav.demoCenter': 'Demo Center',
    'nav.allProfiles': 'Profiles',
    'nav.login': 'Sign In',
    'nav.logout': 'Sign Out',
    'nav.switchRole': 'Switch Role',

    // Role switcher
    'role.caregiver': 'Caregiver',
    'role.senior': 'Senior',
    'role.viewAsSenior': 'View as Senior',
    'role.viewAsCaregiver': 'View as Caregiver',

    // Language options
    'lang.en': 'English',
    'lang.ta': 'தமிழ் (Tamil)',
    'lang.hi': 'हिन्दी (Hindi)',
    'lang.select': 'Language',

    // Elderly Dashboard
    'elderly.headerTitle': 'Senior Care Dashboard',
    'elderly.greeting': 'Good day, {name}!',
    'elderly.todaysReminders': "TODAY'S REMINDERS",
    'elderly.nextReminder': 'NEXT SCHEDULED REMINDER',
    'elderly.allCaughtUp': 'All reminders for today are confirmed! Wonderful job.',
    'elderly.taken': 'TAKEN',
    'elderly.notYet': 'NOT YET',
    'elderly.readOutLoud': 'Read Out Loud',
    'elderly.talkToCareAI': 'TALK TO CAREAI',
    'elderly.contactCaregiver': 'CONTACT CAREGIVER',
    'elderly.emergencyContact': 'EMERGENCY CONTACT',
    'elderly.caregiverNotified': 'Priya Caregiver is active and updated.',
    'elderly.needHelp': 'Need assistance with your schedule? Press below.',
    'elderly.confirmedTakenTitle': 'Medication Confirmed Taken!',
    'elderly.confirmedTakenSub': 'Priya has been updated. Next scheduled reminder will alert automatically.',
    'elderly.scheduledDoses': '{count} Scheduled Doses',
    'elderly.dailyScheduleVerified': 'Daily Schedule • Verified by Priya Caregiver',
    'elderly.callPriya': 'Call Priya (+91 98765 43210)',
    'elderly.physicianAndAmbulance': 'Physician & Ambulance (108/112)',
    
    // Reminder Statuses
    'status.UPCOMING': 'Upcoming',
    'status.DUE': 'Due Now',
    'status.PENDING': 'Pending (Not Yet)',
    'status.TAKEN': 'Taken & Confirmed',
    'status.NOT_CONFIRMED': 'Not Confirmed',
    'status.FOLLOW_UP': 'Follow-Up Reminder',
    'status.ESCALATED': 'Escalated Alert',

    // Care Loop
    'careloop.title': 'The CareAI Closed-Loop Escalation Cycle',
    'careloop.active': 'Active State',
    'careloop.step': 'Care Loop Step {step}/5',
    'careloop.stage1.title': 'Medication Scheduled',
    'careloop.stage1.sub': 'Caregiver sets daily times',
    'careloop.stage1.time': '08:00 AM',
    'careloop.stage2.title': 'Reminder Sent',
    'careloop.stage2.sub': 'Elderly alerted visually & chime',
    'careloop.stage2.time': '08:00 AM',
    'careloop.stage3.title': 'Elderly Response',
    'careloop.stage3.sub': 'Selects TAKEN or NOT YET',
    'careloop.stage3.time': '08:05 AM',
    'careloop.stage4.title': 'Follow-Up Reminder',
    'careloop.stage4.sub': 'Automatic gentle re-prompt',
    'careloop.stage4.time': '08:15 AM (+15m)',
    'careloop.stage5.title': 'Caregiver Alert',
    'careloop.stage5.sub': 'Family notified unconfirmed',
    'careloop.stage5.time': '08:30 AM (+30m)',

    // Caregiver Command Center
    'caregiver.commandCenter': 'Caregiver Command Center',
    'caregiver.welcome': 'Welcome, Priya Caregiver',
    'caregiver.supervising': 'Supervising schedule adherence for {name}',
    'caregiver.selectSenior': 'Select Senior:',
    'caregiver.addMedication': 'Add Medication',
    'caregiver.viewSeniorScreen': "View {name}'s Screen",
    'caregiver.allProfiles': 'All Profiles',
    'caregiver.totalMedicines': 'Total Medicines',
    'caregiver.completedToday': 'Completed Today',
    'caregiver.pendingFollowUp': 'Pending / Follow-up',
    'caregiver.alerts': 'Caregiver Alerts',
    'caregiver.activeAlerts': 'Active Caregiver Alerts',
    'caregiver.urgentAttention': 'requires immediate attention. Unconfirmed reminder past 30-minute threshold.',
    'caregiver.callSenior': 'Call {name}',
    'caregiver.callPhysician': 'Call Doctor',
    'caregiver.markResolved': 'Mark Taken & Resolve',
    'caregiver.todaysScheduleTitle': "Today's Schedule & Real-Time Status",
    'caregiver.allSeniorsOnSchedule': 'All seniors currently on schedule. No unconfirmed reminders.',
    'caregiver.colMedicine': 'Medication',
    'caregiver.colTime': 'Scheduled Time',
    'caregiver.colFrequency': 'Frequency',
    'caregiver.colState': 'Care Loop State',
    'caregiver.colActions': 'Actions',
    'caregiver.actionSimulateAlert': 'Simulate Alert (+30m)',
    'caregiver.dailyProgress': 'Daily Schedule Progress',
    'caregiver.adherenceGoal': 'Adherence Goal: 100%',
    'caregiver.allDosesCompleted': 'All doses completed today! Superb compliance.',
    'caregiver.recentHistoryTitle': 'Recent Compliance & Escalation History',
    'caregiver.viewAllHistory': 'View All History',
    'caregiver.colTimestamp': 'Timestamp',
    'caregiver.colSenior': 'Senior',
    'caregiver.colEvent': 'Event',
    'caregiver.colRecordedStatus': 'Recorded Status',
    'caregiver.colNotes': 'Notes',
    'caregiver.liveCareLoopTitle': 'Live Care Loop Cycle',
    'caregiver.emergencyDirectoryTitle': 'Emergency Response & Contacts',
    'caregiver.mother': 'Mother',
    'caregiver.father': 'Father',

    // Medication Schedule Manager
    'medicines.title': 'Medication Schedule Manager',
    'medicines.manageScheduleFor': 'Managing schedule for {name}',
    'medicines.addNewMedication': 'Add New Medication',
    'medicines.safetyDirective': 'Safety Directive: CareAI helps manage reminders and family awareness. It does not provide dosage or medical advice. Consult prescribing healthcare providers before altering schedules.',
    'medicines.emptyTitle': 'No medications scheduled for {name}',
    'medicines.emptySub': 'Click "Add New Medication" to register a schedule.',
    'medicines.active': 'Active',
    'medicines.suspended': 'Suspended',
    'medicines.pause': 'Pause',
    'medicines.activate': 'Activate',
    'medicines.edit': 'Edit Schedule',
    'medicines.remove': 'Remove Schedule',
    'medicines.confirmRemove': 'Are you sure you want to remove "{name}" from the schedule?',
    'medicines.formAddTitle': 'Add New Medication Schedule',
    'medicines.formEditTitle': 'Edit Medication Schedule',
    'medicines.formTargetSenior': 'Target Elderly User *',
    'medicines.formMedName': 'Medication Name *',
    'medicines.formMedPlaceholder': 'e.g. Morning Blood Pressure Medicine',
    'medicines.formNoDosageNote': 'Do not include dosage figures in the title to maintain safety standards.',
    'medicines.formScheduledTime': 'Scheduled Reminder Time (24H) *',
    'medicines.formTimeNote': 'Follow-up triggers +15m; Escalation alert triggers +30m.',
    'medicines.formFrequency': 'Frequency *',
    'medicines.freqDaily': 'Daily',
    'medicines.freqTwiceDaily': 'Twice Daily',
    'medicines.freqWeekly': 'Weekly',
    'medicines.freqAsNeeded': 'As Needed',
    'medicines.formStartDate': 'Start Date *',
    'medicines.formActiveStatus': 'Active Status',
    'medicines.formActiveLabel': 'Active in Care Loop',
    'medicines.formSuspendedLabel': 'Schedule Suspended',
    'medicines.formCaregiverNotes': 'Caregiver Notes (Optional)',
    'medicines.formNotesPlaceholder': 'e.g. Schedule after breakfast with warm water',
    'medicines.cancel': 'Cancel',
    'medicines.saveNew': 'Create Medication Schedule',
    'medicines.saveUpdate': 'Update Schedule',
    'medicines.saving': 'Saving...',

    // History Page
    'history.title': 'Medication Compliance & Audit Logs',
    'history.subtitle': 'Complete immutable record of all reminder transitions, responses, and caregiver escalations.',
    'history.filterAll': 'All Logs',
    'history.filterTaken': 'Confirmed Taken',
    'history.filterEscalated': 'Alerts & Escalations',
    'history.exportCsv': 'Export Audit Log (CSV)',

    // Senior Profiles Page
    'profiles.title': 'Assigned Senior Profiles',
    'profiles.subtitle': "Multiple senior management: Supervised profiles under Priya's care",
    'profiles.selectAsActive': 'Select as Active',
    'profiles.seniorView': 'Senior View',
    'profiles.activeInDashboard': 'Active in Dashboard',
    'profiles.todaysReminders': "Today's Reminders",
    'profiles.completed': 'Completed',
    'profiles.pending': 'Pending',
    'profiles.emergencyContacts': 'Emergency & Clinical Contacts',
    'profiles.primaryPhysician': 'Primary Physician',
    'profiles.physicianPhone': 'Physician Phone',
    'profiles.nationalAmbulance': 'National Ambulance',
    'profiles.scheduleAndLocalization': 'Schedule & Localization',
    'profiles.preferredLanguage': 'Preferred Language',
    'profiles.isolationEnforced': 'Medication Isolation: Strictly Enforced',
    'profiles.relationship': 'Relationship',

    // AI Assistant
    'ai.title': 'CareAI Voice & Schedule Assistant',
    'ai.subtitle': 'Verified reminders assistance. Strictly adheres to healthcare safety.',
    'ai.disclaimer': 'CareAI provides reminder and schedule awareness. It cannot prescribe, diagnose, or advise on dosages.',
    'ai.pressToSpeak': 'Press to Speak',
    'ai.listening': 'Listening...',
    'ai.send': 'Send Query',
    'ai.placeholder': 'Ask: What reminders do I have today?',
    'ai.suggestedTitle': 'Suggested Questions',
    'ai.q1': 'What reminders do I have today?',
    'ai.q2': 'What is my next reminder?',
    'ai.q3': 'Have I confirmed my morning reminder?',
    'ai.q4': 'What is the dosage of my medicine? (Tests AI Safety)',
    'ai.activeLanguage': 'Active Assistant Language:',
    'ai.clear': 'Clear History',

    // Demo Center & Floating Bar
    'demo.title': 'CareAI Closed-Loop Verification Suite',
    'demo.subtitle': 'Demonstrates the 30-minute closed-loop escalation system, deterministic safety gatekeeper, and isolated multi-senior management.',
    'demo.reset': '[ RESET DEMO ]',
    'demo.trigger': '[ TRIGGER REMINDER ]',
    'demo.followup': '[ SIMULATE +15 MIN ]',
    'demo.escalate': '[ SIMULATE +30 MIN ]',
    'demo.taken': '[ MARK TAKEN ]',
    'demo.caregiverAlert': '[ TRIGGER CAREGIVER ALERT ]',
    'demo.resetDesc': 'Restores initial state: Lakshmi (3 reminders, 2 completed, 1 pending) and Raman (4 completed).',
    'demo.triggerDesc': 'Moves target reminder into DUE state. Audible chime and primary action card appear for senior.',
    'demo.followupDesc': 'Simulates 15 minutes elapsed without response. Triggers gentle follow-up reminder chime.',
    'demo.escalateDesc': 'Simulates 30 minutes elapsed without confirmation. Escalates and notifies Priya Caregiver.',
    'demo.takenDesc': 'Simulates senior tapping TAKEN. Confirms adherence, writes audit log, and stops escalation.',
    'demo.alertDesc': 'Directly dispatches emergency caregiver alert banner and persistent push notification.',
    'demo.barTitle': 'CareAI Escalation Simulator',
    'demo.fullScreen': 'Full Demo Screen',
    'demo.controlSuiteTitle': 'Required Hackathon Control Suite',
    'demo.caregiverAlertDesc': 'Directly dispatches emergency caregiver alert banner and persistent push notification.',
    'demo.safetyGatekeeperTitle': 'Deterministic Safety Gatekeeper',
    'demo.safetyGatekeeperSub': 'Live AI Safety & Clinical Boundary Testing',
    'demo.safetyGatekeeperDesc': 'Test how server-side safety interceptors prevent dosage hallucinations and medical diagnosis before invoking Gemini.',
    'demo.testDosageBlock': 'Test Dosage Block',
    'demo.testEmergencyRedirect': 'Test Emergency Redirect',
    'demo.testScheduleSafe': 'Test Schedule Safe Query',
    'demo.runQuery': 'Run Query',
    'demo.classifiedCategory': 'Classified Category',
    'demo.responsePayload': 'Response Payload',
    'demo.languageArchitecture': 'Multilingual Architecture',
    'demo.languageArchitectureTitle': 'English, Tamil & Hindi Dual/Tri Interface',
    'demo.languageArchitectureDesc': 'CareAI features full vocabulary translation for seniors in vernacular regions. Test switching between English, Tamil, and Hindi instantly.',
    'demo.urgentRedirection': 'Urgent Redirection',
    'demo.emergencyDesc': 'Provides single-tap direct dialing to Priya Caregiver, Dr. Rajesh Kumar, and the national ambulance network (108/112).',
    'demo.launchEmergency': 'Launch Emergency Modal',

    // Medicines & Form Keys
    'medicines.assignedSenior': 'Target Senior',
    'medicines.targetSenior': 'Target Elderly User',
    'medicines.nameLabel': 'Medication Name',
    'medicines.noDosageHint': 'Do not include dosage figures in the title to maintain safety standards.',
    'medicines.timeLabel': 'Scheduled Reminder Time (24H)',
    'medicines.frequencyLabel': 'Frequency',
    'medicines.daily': 'Daily',
    'medicines.twiceDaily': 'Twice Daily',
    'medicines.weekly': 'Weekly',
    'medicines.asNeeded': 'As Needed',
    'medicines.startDateLabel': 'Start Date',
    'medicines.statusLabel': 'Active Status',
    'medicines.activeInLoop': 'Active in Care Loop',
    'medicines.scheduleSuspended': 'Schedule Suspended',
    'medicines.notesLabel': 'Caregiver Notes (Optional)',
    'medicines.updateSchedule': 'Update Schedule',
    'medicines.createSchedule': 'Create Medication Schedule',
    'medicines.addSchedule': 'Add New Medication Schedule',
    'medicines.editSchedule': 'Edit Medication Schedule',

    // History Keys
    'history.searchPlaceholder': 'Search by medication or notes...',
    'history.allStatuses': 'All Statuses',
    'history.reset': 'Reset',
    'history.noRecords': 'No compliance history logs match the selected filters.',
    'history.date': 'Date',
    'history.logged': 'Logged',
    'history.complianceAuditFooter': 'Compliance Audit Trail: Immutable chronological record of elder responses and caregiver escalations.',

    // Caregiver Extras
    'caregiver.activeSeniorBadge': 'Active in Dashboard',
    'caregiver.selectActive': 'Select as Active',

    // AI Assistant Extras
    'ai.assistantSub': 'Verified Healthcare Schedule Intelligence',
    'ai.muteVoice': 'Mute Voice',
    'ai.safetyConstraint': 'Safety Constraint: CareAI answers strictly from verified stored medication reminders. It will never provide dosage, changes, or diagnosis.',
    'ai.safetyBoundaryEnforced': 'Safety Boundary Enforced',
    'ai.speak': 'Speak',
    'ai.verifying': 'CareAI is verifying your schedule...',

    // Emergency Contact Modal
    'emergency.title': 'Emergency Contact Directory',
    'emergency.subtitle': 'Immediate contact directory for {name}',
    'emergency.ambulanceTitle': 'National Emergency Ambulance',
    'emergency.primaryCaregiver': 'Primary Family Caregiver',
    'emergency.familyDoctor': 'Family Physician',
    'emergency.call': 'Call Now',
    'emergency.close': 'Close Window'
  },

  ta: {
    // Branding & Header
    'app.name': 'CareAI',
    'app.tagline': 'முதியவர்கள் நேரத்திற்கு மருந்து உட்கொள்ளவும், குடும்பத்தினர் விழிப்புடன் இருக்கவும் உதவுகிறது.',
    'app.subtitle': 'முதியோர் பராமரிப்பு மற்றும் தானியங்கி நினைவூட்டல் தளம்',
    
    // Navigation & Common
    'nav.home': 'முகப்பு',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.elderly': 'முதியோர் பார்வை',
    'nav.caregiver': 'பராமரிப்பாளர் பார்வை',
    'nav.medicines': 'மருந்துகள்',
    'nav.history': 'வரலாறு',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.assistant': 'AI உதவியாளர்',
    'nav.settings': 'அமைப்புகள்',
    'nav.demo': 'டெமோ உருவகப்படுத்துதல்',
    'nav.demoCenter': 'டெமோ மையம்',
    'nav.allProfiles': 'சுயவிவரங்கள்',
    'nav.login': 'உள்நுழைக',
    'nav.logout': 'வெளியேறு',
    'nav.switchRole': 'பயனர் மாற்றம்',

    // Role switcher
    'role.caregiver': 'பராமரிப்பாளர்',
    'role.senior': 'முதியவர்',
    'role.viewAsSenior': 'முதியோர் பார்வைக்கு மாறுக',
    'role.viewAsCaregiver': 'பராமரிப்பாளர் பார்வைக்கு மாறுக',

    // Language options
    'lang.en': 'English',
    'lang.ta': 'தமிழ் (Tamil)',
    'lang.hi': 'हिन्दी (Hindi)',
    'lang.select': 'மொழி',

    // Elderly Dashboard
    'elderly.headerTitle': 'முதியோர் பராமரிப்பு டாஷ்போர்டு',
    'elderly.greeting': 'வணக்கம், {name}!',
    'elderly.todaysReminders': 'இன்றைய நினைவூட்டல்கள்',
    'elderly.nextReminder': 'அடுத்த மருந்து நேரம்',
    'elderly.allCaughtUp': 'இன்றைய அனைத்து மருந்துகளும் உறுதி செய்யப்பட்டன! நன்று.',
    'elderly.taken': 'சாப்பிட்டாயிற்று',
    'elderly.notYet': 'இன்னும் இல்லை',
    'elderly.readOutLoud': 'வாசித்துக் காட்டு',
    'elderly.talkToCareAI': 'CareAI உடன் பேசுக',
    'elderly.contactCaregiver': 'பராமரிப்பாளரை அழைக்க',
    'elderly.emergencyContact': 'அவசர தொடர்பு',
    'elderly.caregiverNotified': 'பராமரிப்பாளர் பிரியா தகவல்களைப் பெற்று வருகிறார்.',
    'elderly.needHelp': 'உதவி தேவையா? கீழே அழுத்தவும்.',
    'elderly.confirmedTakenTitle': 'மருந்து உட்கொள்ளப்பட்டது உறுதி செய்யப்பட்டது!',
    'elderly.confirmedTakenSub': 'பிரியாவுக்கு தகவல் தெரிவிக்கப்பட்டது. அடுத்த நினைவூட்டல் தானாக ஒலிக்கும்.',
    'elderly.scheduledDoses': '{count} திட்டமிடப்பட்ட மருந்துகள்',
    'elderly.dailyScheduleVerified': 'தினசரி அட்டவணை • பிரியாவால் சரிபார்க்கப்பட்டது',
    'elderly.callPriya': 'பிரியாவை அழைக்க (+91 98765 43210)',
    'elderly.physicianAndAmbulance': 'மருத்துவர் & ஆம்புலன்ஸ் (108/112)',
    
    // Reminder Statuses
    'status.UPCOMING': 'வரவிருக்கிறது',
    'status.DUE': 'உட்கொள்ளும் நேரம்',
    'status.PENDING': 'நிலுவையில் (இன்னும் இல்லை)',
    'status.TAKEN': 'உட்கொள்ளப்பட்டது',
    'status.NOT_CONFIRMED': 'உறுதிப்படுத்தப்படவில்லை',
    'status.FOLLOW_UP': 'தொடர் நினைவூட்டல்',
    'status.ESCALATED': 'பராமரிப்பாளர் எச்சரிக்கை',

    // Care Loop
    'careloop.title': 'CareAI தானியங்கி சுழற்சி',
    'careloop.active': 'செயலில் உள்ள நிலை',
    'careloop.step': 'சுழற்சி நிலை {step}/5',
    'careloop.stage1.title': 'மருந்து அட்டவணை',
    'careloop.stage1.sub': 'பராமரிப்பாளர் நேரம் நிர்ணயிக்கிறார்',
    'careloop.stage1.time': 'காலை 08:00',
    'careloop.stage2.title': 'நினைவூட்டல் அனுப்புதல்',
    'careloop.stage2.sub': 'ஒலி மற்றும் காட்சி எச்சரிக்கை',
    'careloop.stage2.time': 'காலை 08:00',
    'careloop.stage3.title': 'முதியவர் பதில்',
    'careloop.stage3.sub': 'சாப்பிட்டேன் / இன்னும் இல்லை',
    'careloop.stage3.time': 'காலை 08:05',
    'careloop.stage4.title': 'தொடர் நினைவூட்டல்',
    'careloop.stage4.sub': 'தானியங்கி மென்மையான எச்சரிக்கை',
    'careloop.stage4.time': 'காலை 08:15 (+15 நிமி)',
    'careloop.stage5.title': 'பராமரிப்பாளர் எச்சரிக்கை',
    'careloop.stage5.sub': 'குடும்பத்தினருக்கு அவசர தகவல்',
    'careloop.stage5.time': 'காலை 08:30 (+30 நிமி)',

    // Caregiver Command Center
    'caregiver.commandCenter': 'பராமரிப்பாளர் கட்டுப்பாட்டு மையம்',
    'caregiver.welcome': 'வணக்கம், பிரியா (பராமரிப்பாளர்)',
    'caregiver.supervising': '{name} அவர்களின் மருந்து அட்டவணை மேற்பார்வை',
    'caregiver.selectSenior': 'முதியவரைத் தேர்ந்தெடுக்கவும்:',
    'caregiver.addMedication': 'புதிய மருந்து சேர்க்க',
    'caregiver.viewSeniorScreen': '{name} திரையைக் காண்க',
    'caregiver.allProfiles': 'அனைத்து சுயவிவரங்கள்',
    'caregiver.totalMedicines': 'மொத்த மருந்துகள்',
    'caregiver.completedToday': 'இன்று உட்கொள்ளப்பட்டவை',
    'caregiver.pendingFollowUp': 'நிலுவை / தொடர் நினைவூட்டல்',
    'caregiver.alerts': 'அவசர எச்சரிக்கைகள்',
    'caregiver.activeAlerts': 'செயலில் உள்ள அவசர எச்சரிக்கைகள்',
    'caregiver.urgentAttention': 'உடனடி கவனம் தேவை. 30 நிமிடங்களுக்கு மேலாக உறுதிப்படுத்தப்படவில்லை.',
    'caregiver.callSenior': '{name} அவர்களை அழைக்க',
    'caregiver.callPhysician': 'மருத்துவரை அழைக்க',
    'caregiver.markResolved': 'சாப்பிட்டதாக உறுதி செய்',
    'caregiver.todaysScheduleTitle': 'இன்றைய அட்டவணை மற்றும் நேரடி நிலை',
    'caregiver.allSeniorsOnSchedule': 'அனைவரும் சரியான நேரத்தில் உள்ளனர். எச்சரிக்கைகள் ஏதுமில்லை.',
    'caregiver.colMedicine': 'மருந்து',
    'caregiver.colTime': 'திட்டமிடப்பட்ட நேரம்',
    'caregiver.colFrequency': 'அதிர்வெண்',
    'caregiver.colState': 'சுழற்சி நிலை',
    'caregiver.colActions': 'செயல்கள்',
    'caregiver.actionSimulateAlert': 'எச்சரிக்கையை உருவாக்கு (+30 நிமி)',
    'caregiver.dailyProgress': 'இன்றைய முன்னேற்ற விகிதம்',
    'caregiver.adherenceGoal': 'இலக்கு: 100%',
    'caregiver.allDosesCompleted': 'இன்றைய அனைத்து மருந்துகளும் முடிக்கப்பட்டன!',
    'caregiver.recentHistoryTitle': 'சமீபத்திய வரலாறு மற்றும் பதிவுகள்',
    'caregiver.viewAllHistory': 'முழு வரலாற்றைக் காண்க',
    'caregiver.colTimestamp': 'நேரம்',
    'caregiver.colSenior': 'முதியவர்',
    'caregiver.colEvent': 'நிகழ்வு',
    'caregiver.colRecordedStatus': 'பதிவு செய்யப்பட்ட நிலை',
    'caregiver.colNotes': 'குறிப்புகள்',
    'caregiver.liveCareLoopTitle': 'நேரடி CareAI சுழற்சி',
    'caregiver.emergencyDirectoryTitle': 'அவசர தொடர்பு எண்கள்',
    'caregiver.mother': 'தாய்',
    'caregiver.father': 'தந்தை',

    // Medication Schedule Manager
    'medicines.title': 'மருந்து அட்டவணை மேலாளர்',
    'medicines.manageScheduleFor': '{name} அவர்களின் அட்டவணை மேலாண்மை',
    'medicines.addNewMedication': 'புதிய மருந்து சேர்க்க',
    'medicines.safetyDirective': 'பாதுகாப்பு விதி: CareAI நினைவூட்டல்களை மட்டுமே நிர்வகிக்கிறது. இது மருந்தளவு அல்லது மருத்துவ ஆலோசனைகளை வழங்காது.',
    'medicines.emptyTitle': '{name} அவர்களுக்கு மருந்துகள் ஏதுமில்லை',
    'medicines.emptySub': 'அட்டவணையை பதிவு செய்ய "புதிய மருந்து சேர்க்க" என்பதை அழுத்தவும்.',
    'medicines.active': 'செயலில்',
    'medicines.suspended': 'நிறுத்திவைக்கப்பட்டது',
    'medicines.pause': 'தற்காலிகமாக நிறுத்து',
    'medicines.activate': 'செயல்படுத்து',
    'medicines.edit': 'அட்டவணையைத் திருத்து',
    'medicines.remove': 'நீக்கு',
    'medicines.confirmRemove': 'இதை அட்டவணையில் இருந்து நிச்சயமாக நீக்க வேண்டுமா?',
    'medicines.formAddTitle': 'புதிய மருந்து அட்டவணை சேர்க்க',
    'medicines.formEditTitle': 'மருந்து அட்டவணையைத் திருத்து',
    'medicines.formTargetSenior': 'முதியவர் தேர்வு *',
    'medicines.formMedName': 'மருந்தின் பெயர் *',
    'medicines.formMedPlaceholder': 'எ.கா: காலை ரத்த அழுத்த மருந்து',
    'medicines.formNoDosageNote': 'பாதுகாப்பிற்காக மருந்தின் தலைப்பில் அளவைக் குறிப்பிட வேண்டாம்.',
    'medicines.formScheduledTime': 'நினைவூட்டல் நேரம் (24 மணி) *',
    'medicines.formTimeNote': '+15 நிமிடத்தில் தொடர் நினைவூட்டல்; +30 நிமிடத்தில் எச்சரிக்கை செல்லும்.',
    'medicines.formFrequency': 'அதிர்வெண் *',
    'medicines.freqDaily': 'தினசரி',
    'medicines.freqTwiceDaily': 'ஒரு நாளைக்கு இருமுறை',
    'medicines.freqWeekly': 'வாராந்திர',
    'medicines.freqAsNeeded': 'தேவைப்படும் போது',
    'medicines.formStartDate': 'தொடக்க தேதி *',
    'medicines.formActiveStatus': 'செயல் நிலை',
    'medicines.formActiveLabel': 'சுழற்சியில் செயலில் உள்ளது',
    'medicines.formSuspendedLabel': 'நிறுத்தப்பட்டுள்ளது',
    'medicines.formCaregiverNotes': 'பராமரிப்பாளர் குறிப்புகள் (விரும்பினால்)',
    'medicines.formNotesPlaceholder': 'எ.கா: காலை உணவுக்குப் பின் வெதுவெதுப்பான நீரில் எடுக்கவும்',
    'medicines.cancel': 'ரத்துசெய்',
    'medicines.saveNew': 'அட்டவணையை உருவாக்கு',
    'medicines.saveUpdate': 'அட்டவணையைப் புதுப்பி',
    'medicines.saving': 'சேமிக்கப்படுகிறது...',

    // History Page
    'history.title': 'மருந்து உட்கொள்ளல் தணிக்கை பதிவுகள்',
    'history.subtitle': 'அனைத்து நினைவூட்டல் மாற்றங்கள், பதில்கள் மற்றும் அவசர எச்சரிக்கைகளின் முழுமையான பதிவு.',
    'history.filterAll': 'அனைத்து பதிவுகள்',
    'history.filterTaken': 'சாப்பிட்டவை மட்டும்',
    'history.filterEscalated': 'எச்சரிக்கைகள் மட்டும்',
    'history.exportCsv': 'CSV ஆக பதிவிறக்கு',

    // Senior Profiles Page
    'profiles.title': 'முதியோர் சுயவிவரங்கள்',
    'profiles.subtitle': 'பிரியாவின் பராமரிப்பில் உள்ள முதியோர்களின் விவரங்கள்',
    'profiles.selectAsActive': 'செயலில் உள்ளவராகத் தேர்ந்தெடு',
    'profiles.seniorView': 'முதியோர் பார்வை',
    'profiles.activeInDashboard': 'டாஷ்போர்டில் செயலில் உள்ளது',
    'profiles.todaysReminders': 'இன்றைய நினைவூட்டல்கள்',
    'profiles.completed': 'முடிக்கப்பட்டவை',
    'profiles.pending': 'நிலுவையில் உள்ளவை',
    'profiles.emergencyContacts': 'அவசர & மருத்துவ தொடர்புகள்',
    'profiles.primaryPhysician': 'முதன்மை மருத்துவர்',
    'profiles.physicianPhone': 'மருத்துவர் தொலைபேசி',
    'profiles.nationalAmbulance': 'தேசிய ஆம்புலன்ஸ் எண்',
    'profiles.scheduleAndLocalization': 'அட்டவணை & மொழி விருப்பம்',
    'profiles.preferredLanguage': 'விருப்பமான மொழி',
    'profiles.isolationEnforced': 'மருந்து தனிமைப்படுத்தல்: கண்டிப்பாக பின்பற்றப்படுகிறது',
    'profiles.relationship': 'உறவுமுறை',

    // AI Assistant
    'ai.title': 'CareAI குரல் மற்றும் அட்டவணை உதவியாளர்',
    'ai.subtitle': 'உறுதிப்படுத்தப்பட்ட அட்டவணை உதவி. மருத்துவ பாதுகாப்பு விதிகளுக்கு உட்பட்டது.',
    'ai.disclaimer': 'CareAI நினைவூட்டல்களை மட்டுமே நிர்வகிக்கிறது. மருந்தளவு அல்லது நோயறிதல் ஆலோசனைகளை வழங்காது.',
    'ai.pressToSpeak': 'பேச அழுத்தவும்',
    'ai.listening': 'கேட்கிறது...',
    'ai.send': 'அனுப்புக',
    'ai.placeholder': 'கேளுங்கள்: இன்று என்ன மருந்துகள் உள்ளன?',
    'ai.suggestedTitle': 'பரிந்துரைக்கப்பட்ட கேள்விகள்',
    'ai.q1': 'இன்று எனக்கு என்ன நினைவூட்டல்கள் உள்ளன?',
    'ai.q2': 'எனது அடுத்த மருந்து என்ன?',
    'ai.q3': 'காலை மருந்தை நான் உறுதிப்படுத்தினேனா?',
    'ai.q4': 'மருந்தின் அளவு என்ன? (பாதுகாப்பு சோதனை)',
    'ai.activeLanguage': 'செயலில் உள்ள மொழி:',
    'ai.clear': 'வரலாற்றை அழி',

    // Demo Center & Floating Bar
    'demo.title': 'CareAI நேரடி சரிபார்ப்பு மையம்',
    'demo.subtitle': '30 நிமிட தானியங்கி சுழற்சி, பாதுகாப்பு விதிகள் மற்றும் பல-முதியோர் மேலாண்மையை விளக்குகிறது.',
    'demo.reset': '[ மீட்டமை (RESET) ]',
    'demo.trigger': '[ நினைவூட்டு (TRIGGER) ]',
    'demo.followup': '[ +15 நிமி உருவகப்படுத்து ]',
    'demo.escalate': '[ +30 நிமி எச்சரிக்கை செய் ]',
    'demo.taken': '[ சாப்பிட்டதாகப் பதிவு செய் ]',
    'demo.caregiverAlert': '[ நேரடி எச்சரிக்கை அனுப்பு ]',
    'demo.resetDesc': 'ஆரம்ப நிலையை மீட்டமைக்கிறது: லட்சுமி (3 மருந்துகள், 2 முடிந்தது, 1 நிலுவை) மற்றும் ராமன் (4 முடிந்தது).',
    'demo.triggerDesc': 'நினைவூட்டலை நேரடி நிலைக்கு மாற்றுகிறது. ஒலி எச்சரிக்கை ஒலிக்கும்.',
    'demo.followupDesc': 'பதில் அளிக்காத 15 நிமிடங்களை உருவகப்படுத்துகிறது. தொடர் நினைவூட்டல் ஒலிக்கும்.',
    'demo.escalateDesc': '30 நிமிடங்களை உருவகப்படுத்துகிறது. பிரியாவுக்கு அவசர எச்சரிக்கை அனுப்பப்படும்.',
    'demo.takenDesc': 'முதியவர் மருந்தை உட்கொண்டதை பதிவு செய்து சுழற்சியை நிறைவு செய்கிறது.',
    'demo.alertDesc': 'நேரடியாக பராமரிப்பாளருக்கு அவசர சிவப்பு எச்சரிக்கை அறிவிப்பை அனுப்புகிறது.',
    'demo.barTitle': 'CareAI எஸ்கலேஷன் சிமுலேட்டர்',
    'demo.fullScreen': 'முழு டெமோ திரை',
    'demo.controlSuiteTitle': 'தேவையான ஹேக்கத்தான் கட்டுப்பாட்டுத் தொகுப்பு',
    'demo.caregiverAlertDesc': 'நேரடியாக பராமரிப்பாளருக்கு அவசர சிவப்பு எச்சரிக்கை அறிவிப்பை அனுப்புகிறது.',
    'demo.safetyGatekeeperTitle': 'பாதுகாப்பு நுழைவாயில்',
    'demo.safetyGatekeeperSub': 'நேரடி AI பாதுகாப்பு மற்றும் மருத்துவ எல்லை சோதனை',
    'demo.safetyGatekeeperDesc': 'ஜெமினி AI-யை அழைப்பதற்கு முன் சர்வர் பக்க பாதுகாப்பு சோதனையாளர் மருந்தளவு தவறுகளையும் மருத்துவ கணிப்புகளையும் எவ்வாறு தடுக்கிறது என்பதை சோதிக்கவும்.',
    'demo.testDosageBlock': 'மருந்தளவு தடுப்பை சோதிக்க',
    'demo.testEmergencyRedirect': 'அவசர திசைதிருப்பலை சோதிக்க',
    'demo.testScheduleSafe': 'பாதுகாப்பான நேர வினவலை சோதிக்க',
    'demo.runQuery': 'வினவலை இயக்கு',
    'demo.classifiedCategory': 'வகைப்படுத்தப்பட்ட பிரிவு',
    'demo.responsePayload': 'பதில் தகவல்',
    'demo.languageArchitecture': 'பன்மொழி வடிவமைப்பு',
    'demo.languageArchitectureTitle': 'தமிழ், ஆங்கிலம் மற்றும் இந்தி இடைமுகம்',
    'demo.languageArchitectureDesc': 'முதியவர்கள் தங்கள் சொந்த மொழியில் எளிதாக பயன்படுத்த முழு சொற்களஞ்சிய மொழிபெயர்ப்பு. ஆங்கிலம், தமிழ், இந்தி இடையே உடனடியாக மாறவும்.',
    'demo.urgentRedirection': 'அவசர திசைதிருப்பல்',
    'demo.emergencyDesc': 'பிரியா, மருத்துவர் ராஜேஷ் குமார் மற்றும் தேசிய ஆம்புலன்ஸ் (108/112) உடனடி அழைப்பு.',
    'demo.launchEmergency': 'அவசர சாளரத்தைத் திறக்க',

    // Medicines & Form Keys
    'medicines.assignedSenior': 'இலக்கு முதியவர்',
    'medicines.targetSenior': 'இலக்கு முதியவர்',
    'medicines.nameLabel': 'மருந்தின் பெயர்',
    'medicines.noDosageHint': 'பாதுகாப்பு காரணங்களுக்காக பெயரில் அளவைக் குறிப்பிட வேண்டாம்.',
    'medicines.timeLabel': 'நினைவூட்டல் நேரம் (24 மணிநேரம்)',
    'medicines.frequencyLabel': 'அதிர்வெண்',
    'medicines.daily': 'தினசரி',
    'medicines.twiceDaily': 'நாளைக்கு இருமுறை',
    'medicines.weekly': 'வாராந்திரம்',
    'medicines.asNeeded': 'தேவைப்படும் போது',
    'medicines.startDateLabel': 'தொடக்க தேதி',
    'medicines.statusLabel': 'செயல்பாட்டு நிலை',
    'medicines.activeInLoop': 'செயலில் உள்ளது',
    'medicines.scheduleSuspended': 'நிறுத்தப்பட்டுள்ளது',
    'medicines.notesLabel': 'குறிப்புகள் (விருப்பத்தேர்வு)',
    'medicines.updateSchedule': 'அட்டவணையைப் புதுப்பி',
    'medicines.createSchedule': 'மருந்து அட்டவணையை உருவாக்கு',
    'medicines.addSchedule': 'புதிய மருந்து அட்டவணையைச் சேர்',
    'medicines.editSchedule': 'மருந்து அட்டவணையைத் திருத்து',

    // History Keys
    'history.searchPlaceholder': 'மருந்து அல்லது குறிப்புகளைத் தேட...',
    'history.allStatuses': 'அனைத்து நிலைகளும்',
    'history.reset': 'மீட்டமைக்க',
    'history.noRecords': 'தேர்ந்தெடுக்கப்பட்ட வடிகட்டிகளுக்கு வரலாற்றுப் பதிவுகள் எதுவும் இல்லை.',
    'history.date': 'தேதி',
    'history.logged': 'பதிவு செய்யப்பட்டது',
    'history.complianceAuditFooter': 'நினைவூட்டல் உறுதிப்படுத்தல்கள் மற்றும் எஸ்கலேஷன்களின் மாற்ற முடியாத காலவரிசை பதிவு.',

    // Caregiver Extras
    'caregiver.activeSeniorBadge': 'டாஷ்போர்டில் செயலில் உள்ளது',
    'caregiver.selectActive': 'செயலில் உள்ளவராகத் தேர்வு செய்',

    // AI Assistant Extras
    'ai.assistantSub': 'சரிபார்க்கப்பட்ட சுகாதார அட்டவணை அறிவுத்திறன்',
    'ai.muteVoice': 'குரலை முடக்கு',
    'ai.safetyConstraint': 'பாதுகாப்பு விதி: CareAI பதிவுசெய்யப்பட்ட மருந்து நினைவூட்டல்களிலிருந்து மட்டுமே பதிலளிக்கும். மருந்தின் அளவை மாற்றவோ, புதிய மருந்துகளை பரிந்துரைக்கவோ செய்யாது.',
    'ai.safetyBoundaryEnforced': 'பாதுகாப்பு எல்லை செயல்படுத்தப்பட்டது',
    'ai.speak': 'ஒலி வடிவில் கேட்க',
    'ai.verifying': 'CareAI உங்கள் அட்டவணையை சரிபார்க்கிறது...',

    // Emergency Contact Modal
    'emergency.title': 'அவசர தொடர்பு எண்கள்',
    'emergency.subtitle': '{name} அவர்களுக்கான அவசர எண்கள்',
    'emergency.ambulanceTitle': 'தேசிய அவசர ஆம்புலன்ஸ் சேவை',
    'emergency.primaryCaregiver': 'முதன்மை குடும்ப பராமரிப்பாளர்',
    'emergency.familyDoctor': 'குடும்ப மருத்துவர்',
    'emergency.call': 'அழைக்க',
    'emergency.close': 'மூடு'
  },

  hi: {
    // Branding & Header
    'app.name': 'CareAI',
    'app.tagline': 'वरिष्ठ नागरिकों को समय पर दवा और परिवारों को सूचित रखने में सहायक।',
    'app.subtitle': 'स्मार्ट बुजुर्ग स्वास्थ्य अनुस्मारक एवं एस्केलेशन प्लेटफॉर्म',
    
    // Navigation & Common
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.elderly': 'वरिष्ठ नागरिक दृश्य',
    'nav.caregiver': 'देखभालकर्ता दृश्य',
    'nav.medicines': 'दवाइयाँ',
    'nav.history': 'इतिहास',
    'nav.notifications': 'सूचनाएँ',
    'nav.assistant': 'AI सहायक',
    'nav.settings': 'सेटिंग्स',
    'nav.demo': 'डेमो सिमुलेशन',
    'nav.demoCenter': 'डेमो केंद्र',
    'nav.allProfiles': 'प्रोफाइल',
    'nav.login': 'लॉग इन',
    'nav.logout': 'लॉग आउट',
    'nav.switchRole': 'भूमिका बदलें',

    // Role switcher
    'role.caregiver': 'देखभालकर्ता',
    'role.senior': 'वरिष्ठ नागरिक',
    'role.viewAsSenior': 'वरिष्ठ नागरिक के रूप में देखें',
    'role.viewAsCaregiver': 'देखभालकर्ता के रूप में देखें',

    // Language options
    'lang.en': 'English',
    'lang.ta': 'தமிழ் (Tamil)',
    'lang.hi': 'हिन्दी (Hindi)',
    'lang.select': 'भाषा',

    // Elderly Dashboard
    'elderly.headerTitle': 'वरिष्ठ नागरिक केयर डैशबोर्ड',
    'elderly.greeting': 'नमस्ते, {name}!',
    'elderly.todaysReminders': 'आज की दवाइयाँ',
    'elderly.nextReminder': 'अगली निर्धारित दवा',
    'elderly.allCaughtUp': 'आज की सभी निर्धारित दवाइयाँ ले ली गई हैं! बहुत बढ़िया।',
    'elderly.taken': 'ले ली',
    'elderly.notYet': 'अभी नहीं',
    'elderly.readOutLoud': 'बोलकर सुनाएँ',
    'elderly.talkToCareAI': 'CareAI से बात करें',
    'elderly.contactCaregiver': 'देखभालकर्ता से संपर्क करें',
    'elderly.emergencyContact': 'आपातकालीन संपर्क',
    'elderly.caregiverNotified': 'देखभालकर्ता प्रिया सक्रिय हैं और अपडेट प्राप्त कर रही हैं।',
    'elderly.needHelp': 'समय सारिणी में सहायता चाहिए? नीचे दबाएँ।',
    'elderly.confirmedTakenTitle': 'दवा ले ली गई है!',
    'elderly.confirmedTakenSub': 'प्रिया को सूचित कर दिया गया है। अगला अनुस्मारक निर्धारित समय पर बजेगा।',
    'elderly.scheduledDoses': '{count} निर्धारित खुराकें',
    'elderly.dailyScheduleVerified': 'दैनिक सारिणी • प्रिया द्वारा सत्यापित',
    'elderly.callPriya': 'प्रिया को कॉल करें (+91 98765 43210)',
    'elderly.physicianAndAmbulance': 'चिकित्सक एवं एम्बुलेंस (108/112)',
    
    // Reminder Statuses
    'status.UPCOMING': 'आगामी',
    'status.DUE': 'लेने का समय',
    'status.PENDING': 'लंबित (अभी नहीं)',
    'status.TAKEN': 'ले ली गई',
    'status.NOT_CONFIRMED': 'अपुष्ट',
    'status.FOLLOW_UP': 'फॉलो-अप अनुस्मारक',
    'status.ESCALATED': 'एस्केलेटेड अलर्ट',

    // Care Loop
    'careloop.title': 'CareAI स्वचालित एस्केलेशन चक्र',
    'careloop.active': 'सक्रिय अवस्था',
    'careloop.step': 'चक्र चरण {step}/5',
    'careloop.stage1.title': 'दवा निर्धारित',
    'careloop.stage1.sub': 'देखभालकर्ता समय तय करते हैं',
    'careloop.stage1.time': 'प्रातः 08:00',
    'careloop.stage2.title': 'अनुस्मारक भेजा गया',
    'careloop.stage2.sub': 'ध्वनि एवं दृश्य अलर्ट',
    'careloop.stage2.time': 'प्रातः 08:00',
    'careloop.stage3.title': 'वरिष्ठ नागरिक की प्रतिक्रिया',
    'careloop.stage3.sub': 'ले ली / अभी नहीं का चयन',
    'careloop.stage3.time': 'प्रातः 08:05',
    'careloop.stage4.title': 'फॉलो-अप अनुस्मारक',
    'careloop.stage4.sub': 'स्वचालित सौम्य अलर्ट',
    'careloop.stage4.time': 'प्रातः 08:15 (+15 मि.)',
    'careloop.stage5.title': 'देखभालकर्ता चेतावनी',
    'careloop.stage5.sub': 'परिवार को आपात सूचना',
    'careloop.stage5.time': 'प्रातः 08:30 (+30 मि.)',

    // Caregiver Command Center
    'caregiver.commandCenter': 'देखभालकर्ता नियंत्रण केंद्र',
    'caregiver.welcome': 'स्वागत है, प्रिया (देखभालकर्ता)',
    'caregiver.supervising': '{name} के दवा अनुपालन की निगरानी',
    'caregiver.selectSenior': 'वरिष्ठ नागरिक चुनें:',
    'caregiver.addMedication': 'नई दवा जोड़ें',
    'caregiver.viewSeniorScreen': '{name} की स्क्रीन देखें',
    'caregiver.allProfiles': 'सभी प्रोफाइल',
    'caregiver.totalMedicines': 'कुल दवाइयाँ',
    'caregiver.completedToday': 'आज पूर्ण',
    'caregiver.pendingFollowUp': 'लंबित / फॉलो-अप',
    'caregiver.alerts': 'चेतावनी अलर्ट',
    'caregiver.activeAlerts': 'सक्रिय आपातकालीन अलर्ट',
    'caregiver.urgentAttention': 'को तत्काल ध्यान की आवश्यकता है। 30 मिनट से अधिक समय से अपुष्ट दवा।',
    'caregiver.callSenior': '{name} को कॉल करें',
    'caregiver.callPhysician': 'डॉक्टर को कॉल करें',
    'caregiver.markResolved': 'पूर्ण चिह्नित करें',
    'caregiver.todaysScheduleTitle': 'आज की सारिणी एवं वास्तविक समय स्थिति',
    'caregiver.allSeniorsOnSchedule': 'सभी वरिष्ठ नागरिक समय पर हैं। कोई अपुष्ट अलर्ट नहीं।',
    'caregiver.colMedicine': 'दवा',
    'caregiver.colTime': 'निर्धारित समय',
    'caregiver.colFrequency': 'आवृत्ति',
    'caregiver.colState': 'चक्र स्थिति',
    'caregiver.colActions': 'कार्रवाई',
    'caregiver.actionSimulateAlert': 'अलर्ट सिमुलेट करें (+30 मि.)',
    'caregiver.dailyProgress': 'दैनिक प्रगति दर',
    'caregiver.adherenceGoal': 'अनुपालन लक्ष्य: 100%',
    'caregiver.allDosesCompleted': 'आज की सभी दवाइयाँ ले ली गई हैं! उत्कृष्ट अनुपालन।',
    'caregiver.recentHistoryTitle': 'हालिया अनुपालन एवं एस्केलेशन इतिहास',
    'caregiver.viewAllHistory': 'संपूर्ण इतिहास देखें',
    'caregiver.colTimestamp': 'समय',
    'caregiver.colSenior': 'वरिष्ठ नागरिक',
    'caregiver.colEvent': 'घटना',
    'caregiver.colRecordedStatus': 'दर्ज स्थिति',
    'caregiver.colNotes': 'टिप्पणी',
    'caregiver.liveCareLoopTitle': 'सक्रिय केयर लूप चक्र',
    'caregiver.emergencyDirectoryTitle': 'आपातकालीन निर्देशिका एवं संपर्क',
    'caregiver.mother': 'माता',
    'caregiver.father': 'पिता',

    // Medication Schedule Manager
    'medicines.title': 'दवा समय-सारिणी प्रबंधक',
    'medicines.manageScheduleFor': '{name} के लिए दवा सारिणी प्रबंधन',
    'medicines.addNewMedication': 'नई दवा जोड़ें',
    'medicines.safetyDirective': 'सुरक्षा निर्देश: CareAI केवल अनुस्मारक और पारिवारिक जागरूकता में मदद करता है। यह खुराक या चिकित्सीय सलाह नहीं देता है।',
    'medicines.emptyTitle': '{name} के लिए कोई दवा निर्धारित नहीं है',
    'medicines.emptySub': 'समय-सारिणी दर्ज करने के लिए "नई दवा जोड़ें" पर क्लिक करें।',
    'medicines.active': 'सक्रिय',
    'medicines.suspended': 'स्थगित',
    'medicines.pause': 'रोकें',
    'medicines.activate': 'सक्रिय करें',
    'medicines.edit': 'संपादित करें',
    'medicines.remove': 'हटाएँ',
    'medicines.confirmRemove': 'क्या आप वाकई इसे समय सारिणी से हटाना चाहते हैं?',
    'medicines.formAddTitle': 'नई दवा सारिणी जोड़ें',
    'medicines.formEditTitle': 'दवा सारिणी संपादित करें',
    'medicines.formTargetSenior': 'वरिष्ठ नागरिक चुनें *',
    'medicines.formMedName': 'दवा का नाम *',
    'medicines.formMedPlaceholder': 'उदा: सुबह की ब्लड प्रेशर की दवा',
    'medicines.formNoDosageNote': 'सुरक्षा नियमों के कारण शीर्षक में खुराक की मात्रा न लिखें।',
    'medicines.formScheduledTime': 'निर्धारित समय (24 घंटे) *',
    'medicines.formTimeNote': '+15 मिनट पर फॉलो-अप; +30 मिनट पर आपात चेतावनी भेजी जाती है।',
    'medicines.formFrequency': 'आवृत्ति *',
    'medicines.freqDaily': 'प्रतिदिन (Daily)',
    'medicines.freqTwiceDaily': 'दिन में दो बार (Twice Daily)',
    'medicines.freqWeekly': 'साप्ताहिक (Weekly)',
    'medicines.freqAsNeeded': 'आवश्यकतानुसार (As Needed)',
    'medicines.formStartDate': 'प्रारंभ तिथि *',
    'medicines.formActiveStatus': 'सक्रिय स्थिति',
    'medicines.formActiveLabel': 'केयर लूप में सक्रिय',
    'medicines.formSuspendedLabel': 'स्थगित',
    'medicines.formCaregiverNotes': 'देखभालकर्ता की टिप्पणी (वैकल्पिक)',
    'medicines.formNotesPlaceholder': 'उदा: नाश्ते के बाद गुनगुने पानी से लें',
    'medicines.cancel': 'रद्द करें',
    'medicines.saveNew': 'दवा सारिणी सहेजें',
    'medicines.saveUpdate': 'सारिणी अपडेट करें',
    'medicines.saving': 'सहेजा जा रहा है...',

    // History Page
    'history.title': 'दवा अनुपालन एवं ऑडिट लॉग',
    'history.subtitle': 'सभी अनुस्मारक परिवर्तनों, प्रतिक्रियाओं और एस्केलेशन का स्थायी एवं सुरक्षित रिकॉर्ड।',
    'history.filterAll': 'सभी लॉग',
    'history.filterTaken': 'ली गई दवाइयाँ',
    'history.filterEscalated': 'चेतावनी एवं अलर्ट',
    'history.exportCsv': 'ऑडिट लॉग निर्यात करें (CSV)',

    // Senior Profiles Page
    'profiles.title': 'नियुक्त वरिष्ठ नागरिक प्रोफाइल',
    'profiles.subtitle': 'प्रिया की देखरेख में पंजीकृत वरिष्ठ नागरिक प्रोफाइल',
    'profiles.selectAsActive': 'सक्रिय प्रोफाइल चुनें',
    'profiles.seniorView': 'वरिष्ठ नागरिक दृश्य',
    'profiles.activeInDashboard': 'डैशबोर्ड में सक्रिय',
    'profiles.todaysReminders': 'आज की दवाइयाँ',
    'profiles.completed': 'पूर्ण',
    'profiles.pending': 'लंबित',
    'profiles.emergencyContacts': 'आपातकालीन एवं चिकित्सीय संपर्क',
    'profiles.primaryPhysician': 'प्राथमिक चिकित्सक',
    'profiles.physicianPhone': 'डॉक्टर का फोन',
    'profiles.nationalAmbulance': 'राष्ट्रीय एम्बुलेंस सेवा',
    'profiles.scheduleAndLocalization': 'सारिणी एवं भाषा प्राथमिकता',
    'profiles.preferredLanguage': 'पसंदीदा भाषा',
    'profiles.isolationEnforced': 'दवा पृथक्करण: कड़ाई से लागू',
    'profiles.relationship': 'संबंध',

    // AI Assistant
    'ai.title': 'CareAI आवाज एवं सारिणी सहायक',
    'ai.subtitle': 'सत्यापित अनुस्मारक सहायता। स्वास्थ्य सुरक्षा नियमों का पूर्ण पालन।',
    'ai.disclaimer': 'CareAI केवल समय सारिणी की जानकारी देता है। यह दवा का नुस्खा, निदान या खुराक नहीं बताता है।',
    'ai.pressToSpeak': 'बोलने के लिए दबाएँ',
    'ai.listening': 'सुन रहा हूँ...',
    'ai.send': 'प्रश्न भेजें',
    'ai.placeholder': 'पूछें: आज मेरी कौन सी दवाइयाँ हैं?',
    'ai.suggestedTitle': 'सुझाए गए प्रश्न',
    'ai.q1': 'आज मुझे कौन सी दवाइयाँ लेनी हैं?',
    'ai.q2': 'मेरी अगली दवा कौन सी है?',
    'ai.q3': 'क्या मैंने सुबह की दवा ले ली है?',
    'ai.q4': 'मेरी दवा की खुराक क्या है? (सुरक्षा परीक्षण)',
    'ai.activeLanguage': 'सक्रिय सहायक भाषा:',
    'ai.clear': 'इतिहास साफ़ करें',

    // Demo Center & Floating Bar
    'demo.title': 'CareAI क्लोज्ड-लूप परीक्षण केंद्र',
    'demo.subtitle': '30 मिनट की स्वचालित एस्केलेशन प्रणाली, सुरक्षा नियमों और बहु-वरिष्ठ नागरिक प्रबंधन का लाइव परीक्षण।',
    'demo.reset': '[ रीसेट डेमो (RESET) ]',
    'demo.trigger': '[ अनुस्मारक चालू करें (TRIGGER) ]',
    'demo.followup': '[ +15 मि. सिमुलेट करें ]',
    'demo.escalate': '[ +30 मि. एस्केलेट करें ]',
    'demo.taken': '[ दवा ले ली (MARK TAKEN) ]',
    'demo.caregiverAlert': '[ सीधा अलर्ट भेजें ]',
    'demo.resetDesc': 'प्रारंभिक स्थिति पुनर्स्थापित करता है: लक्ष्मी (3 दवाइयाँ, 2 पूर्ण, 1 लंबित) और रमण (4 पूर्ण)।',
    'demo.triggerDesc': 'दवा को ड्यू अवस्था में ले जाता है। ऑडियो चेतावनी और कार्ड दिखाई देगा।',
    'demo.followupDesc': 'बिना उत्तर के 15 मिनट बीतने का सिमुलेशन करता है। सौम्य अनुस्मारक बजता है।',
    'demo.escalateDesc': '30 मिनट का सिमुलेशन करता है। प्रिया को तत्काल चेतावनी अलर्ट भेजा जाता है।',
    'demo.takenDesc': 'दवा लेने की पुष्टि करता है, ऑडिट लॉग लिखता है और एस्केलेशन रोकता है।',
    'demo.alertDesc': 'सीधे देखभालकर्ता को लाल आपातकालीन अलर्ट और पुश सूचना भेजता है।',
    'demo.barTitle': 'CareAI एस्केलेशन सिमुलेटर',
    'demo.fullScreen': 'पूर्ण डेमो स्क्रीन',
    'demo.controlSuiteTitle': 'आवश्यक हैकाथॉन नियंत्रण सुइट',
    'demo.caregiverAlertDesc': 'सीधे देखभालकर्ता को आपातकालीन लाल अलर्ट और पुश सूचना भेजता है।',
    'demo.safetyGatekeeperTitle': 'निश्चित सुरक्षा द्वारपाल (गेटकीपर)',
    'demo.safetyGatekeeperSub': 'लाइव AI सुरक्षा और नैदानिक सीमा परीक्षण',
    'demo.safetyGatekeeperDesc': 'परीक्षण करें कि जेमिनी को कॉल करने से पहले सर्वर-साइड सुरक्षा इंटरसेप्टर खुराक के भ्रम और चिकित्सा निदान को कैसे रोकते हैं।',
    'demo.testDosageBlock': 'खुराक प्रतिबंध का परीक्षण करें',
    'demo.testEmergencyRedirect': 'आपातकालीन पुनर्निर्देशन परीक्षण',
    'demo.testScheduleSafe': 'शेड्यूल सुरक्षित प्रश्न परीक्षण',
    'demo.runQuery': 'क्वेरी चलाएँ',
    'demo.classifiedCategory': 'वर्गीकृत श्रेणी',
    'demo.responsePayload': 'प्रतिक्रिया पेलोड',
    'demo.languageArchitecture': 'त्रिभाषीय वास्तुकला',
    'demo.languageArchitectureTitle': 'अंग्रेजी, तमिल और हिन्दी इंटरफेस',
    'demo.languageArchitectureDesc': 'बुजुर्गों के लिए संपूर्ण शब्दावली अनुवाद। अंग्रेजी, तमिल और हिन्दी के बीच तुरंत स्विच करें।',
    'demo.urgentRedirection': 'तत्काल पुनर्निर्देशन',
    'demo.emergencyDesc': 'प्रिया, डॉ. राजेश कुमार और राष्ट्रीय एम्बुलेंस नेटवर्क (108/112) को सीधे डायल करने की सुविधा।',
    'demo.launchEmergency': 'आपातकालीन विंडो खोलें',

    // Medicines & Form Keys
    'medicines.assignedSenior': 'लक्षित वरिष्ठ नागरिक',
    'medicines.targetSenior': 'लक्षित बुजुर्ग उपयोगकर्ता',
    'medicines.nameLabel': 'दवा का नाम',
    'medicines.noDosageHint': 'सुरक्षा कारणों से नाम में खुराक की संख्या न लिखें।',
    'medicines.timeLabel': 'निर्धारित समय (24 घंटे)',
    'medicines.frequencyLabel': 'आवृत्ति',
    'medicines.daily': 'प्रतिदिन',
    'medicines.twiceDaily': 'दिन में दो बार',
    'medicines.weekly': 'साप्ताहिक',
    'medicines.asNeeded': 'ज़रूरत पड़ने पर',
    'medicines.startDateLabel': 'प्रारंभ तिथि',
    'medicines.statusLabel': 'सक्रिय स्थिति',
    'medicines.activeInLoop': 'केयर लूप में सक्रिय',
    'medicines.scheduleSuspended': 'शेड्यूल निलंबित',
    'medicines.notesLabel': 'देखभालकर्ता की टिप्पणियाँ (वैकल्पिक)',
    'medicines.updateSchedule': 'शेड्यूल अपडेट करें',
    'medicines.createSchedule': 'दवा शेड्यूल बनाएँ',
    'medicines.addSchedule': 'नया दवा शेड्यूल जोड़ें',
    'medicines.editSchedule': 'दवा शेड्यूल संपादित करें',

    // History Keys
    'history.searchPlaceholder': 'दवा या नोट से खोजें...',
    'history.allStatuses': 'सभी स्थितियाँ',
    'history.reset': 'रीसेट',
    'history.noRecords': 'चयनित फिल्टर से कोई अनुपालन इतिहास लॉग मेल नहीं खाता।',
    'history.date': 'दिनांक',
    'history.logged': 'दर्ज समय',
    'history.complianceAuditFooter': 'अनुपालन ऑडिट ट्रेल: वरिष्ठ नागरिकों की प्रतिक्रियाओं और देखभालकर्ता के एस्केलेशन का स्थायी कालानुक्रमिक रिकॉर्ड।',

    // Caregiver Extras
    'caregiver.activeSeniorBadge': 'डैशबोर्ड में सक्रिय',
    'caregiver.selectActive': 'सक्रिय के रूप में चुनें',

    // AI Assistant Extras
    'ai.assistantSub': 'सत्यापित स्वास्थ्य सेवा शेड्यूल बुद्धिमत्ता',
    'ai.muteVoice': 'आवाज़ बंद करें',
    'ai.safetyConstraint': 'सुरक्षा नियम: CareAI केवल संग्रहीत दवा अनुस्मारक से उत्तर देता है। यह खुराक बदलने, निदान या चिकित्सा सलाह कभी नहीं देगा।',
    'ai.safetyBoundaryEnforced': 'सुरक्षा सीमा लागू की गई',
    'ai.speak': 'सुनें',
    'ai.verifying': 'CareAI आपका शेड्यूल सत्यापित कर रहा है...',

    // Emergency Contact Modal
    'emergency.title': 'आपातकालीन संपर्क निर्देशिका',
    'emergency.subtitle': '{name} के लिए तत्काल संपर्क निर्देशिका',
    'emergency.ambulanceTitle': 'राष्ट्रीय आपातकालीन एम्बुलेंस',
    'emergency.primaryCaregiver': 'प्राथमिक पारिवारिक देखभालकर्ता',
    'emergency.familyDoctor': 'पारिवारिक चिकित्सक',
    'emergency.call': 'अभी कॉल करें',
    'emergency.close': 'खिड़की बंद करें'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('careai_lang');
      if (saved === 'ta' || saved === 'hi' || saved === 'en') {
        return saved;
      }
    } catch {
      // ignore
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('careai_lang', lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
